# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "dbt_demo_project"
version: "1.8.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "default"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ test_executions_result(database=target.database, schema=target.schema, table_identifier='TEST_EXECUTIONS_RESULT') }}"
  - "{{ dbt_artifacts.upload_results(results) }}"
  
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run
# dbt run or dbt build, all of your models will be built as a view in your data platform.
# The configuration below will override this setting for models in the example folder to
# instead be materialized as tables. Any models you add to the root of the models folder will
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  dbt_demo_project:
    MAT_ALIAS_NAME: null
    DBT_ALIAS_NAME: null
 

models:
  dbt_artifacts:
    +database: DBT_DB_DEV # optional, default is your target database
    +schema: DBT_ARTIFACT_LOGGING # optional, default is your target schema
  elementary:
    +database: DBT_DB_DEV 
    +schema: DBT_ELEMENTARY_LOGGING

tests:
  dbt_demo_project:
    +store_failures: true  # all tests
    +severity: warn  # all tests
    +database: DBT_DB_DEV

vars:
  dbt_demo_project:
    MAT_ALIAS_NAME: null
    DBT_ALIAS_NAME: null