SELECT
    SCHEDULE_NAME, 
    JOB_NAME,
    JOB_TYPE,
    ENVIRONMENTNAME,
    VERSIONNAME,
    ENABLED, 
    DAYSOFMONTH,
    DAYOFWEEK, 
    SUNDAY, 
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY, 
    HOUR, 
    MINUTE,
    TIMEZONE
FROM {{ ref('job_schedules') }}
WHERE PLATFORM_NAME = 'MATILLION'

MINUS

SELECT
    NAME,
    JOBNAME,  
    'ORCHESTRATION' AS JOB_TYPE,
    ENVIRONMENTNAME,
    VERSIONNAME,
    ENABLED, 
    DAYSOFMONTH,
    DAYOFWEEK, 
    SUNDAY, 
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY, 
    HOUR, 
    MINUTE,
    TIMEZONE
FROM {{ source('MATILLION', 'MATILLION_SCHEDULES') }}