SELECT
    SCHEDULE_NAME, 
    JOB_NAME,
    JOB_TYPE,
    ENVIRONMENTNAME,
    VERSIONNAME,
    ENABLED, 
    DAYSOFMONTH,
    DAYOFWEEK, 
    SUNDAY, 
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY, 
    HOUR, 
    MINUTE,
    TIMEZONE,
    INSERTED_BY,
    UPDATED_BY,
    INSERT_DATE,
    UPDATE_DATE
FROM {{ ref('vw_job_schedules') }}
WHERE PLATFORM_NAME = 'MATILLION'

MINUS

SELECT
    SCHEDULE_NAME, 
    JOB_NAME,
    JOB_TYPE,
    ENVIRONMENTNAME,
    VERSIONNAME,
    ENABLED, 
    DAYSOFMONTH,
    DAYOFWEEK, 
    SUNDAY, 
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY, 
    HOUR, 
    MINUTE,
    TIMEZONE,
    INSERTED_BY,
    UPDATED_BY,
    INSERT_DATE,
    UPDATE_DATE
FROM {{ ref('job_schedules') }}
WHERE PLATFORM_NAME = 'MATILLION'