{% macro audit_logging_run_end() %}
    {# Building Audit Table Relation #}
    {%- set database = var("audit_logging_database", target.database) -%}
    {%- set schema = var("audit_logging_schema", "LOGGING") -%}
    {%- set table_identifier = var("audit_logging_table_name", "DBT_RUN_LOG") -%}
    {%- set relation = database ~ '.' ~ schema ~ '.' ~ table_identifier -%}

    {# Building Create Audit Table Query #}
    {{ log("Executing 'CREATE TABLE SQL' for Audit Table", info=True) }}
    {% call statement('audit_create_table_sql') %}
        CREATE TABLE IF NOT EXISTS {{ relation }} (
            INVOCATION_ID VARCHAR(16777216) COMMENT 'UID generated by dbt for each invocation.',
            PROJECT_ID VARCHAR(2000) COMMENT 'UID generated by dbt for each project.',
            PROJECT_NAME VARCHAR(2000) COMMENT 'DBT Project name.',
            ENVIRONMENT_ID VARCHAR(2000) COMMENT 'UID generated by dbt for each environment.',
            ENVIRONMENT_NAME VARCHAR(2000) COMMENT 'Environment name configured in the job.',
            JOB_ID VARCHAR(2000) COMMENT 'UID generated by dbt for each job.',
            JOB_NAME VARCHAR(2000) COMMENT 'DBT Job name.',
            OBJECT_UID VARCHAR(2000) COMMENT 'UID generated by dbt for each Object.',
            OBJECT_NAME VARCHAR(2000) COMMENT 'Name of the dbt object.',
            OBJECT_TYPE VARCHAR(2000) COMMENT 'Type of the dbt object (Source, Model, Seeds, Snpashots).',
            OBJECT_STATUS VARCHAR(2000) COMMENT 'Status of the node execution',
            OBJECT_START_TIME TIMESTAMP_NTZ(9) COMMENT 'Start time of the node execution.',
            OBJECT_END_TIME TIMESTAMP_NTZ(9) COMMENT 'Completion time of the node execution.',
            RUN_START_TIME TIMESTAMP_NTZ(9) COMMENT 'Start time of the job run.',
            WAS_FULL_REFRESH BOOLEAN COMMENT 'Nodes run was a full refresh or not.',
            THREAD_ID VARCHAR(2000) COMMENT 'Details of the thread.',
            RUN_STATUS VARCHAR(2000) COMMENT 'Status of the run execution.',
            COMPILE_START_TIME TIMESTAMP_NTZ(9) COMMENT 'Start time of the nodecompile.',
            RUN_END_TIME TIMESTAMP_NTZ(9) COMMENT 'Completion time of the node run.',
            DURATION VARCHAR(2000) COMMENT 'Duration of the node run.',
            SOURCE_RECORD_COUNT NUMBER(38,0) COMMENT 'Row count of source table.',
            INSERT_RECORD_COUNT NUMBER(38,0) COMMENT 'Insert Row count of Target table.',
            UPDATE_RECORD_COUNT NUMBER(38,0) COMMENT 'Updare Row count of Target table.',
            ERROR_RECORD_COUNT NUMBER(38,0) COMMENT 'Error records Row count.',
            MATERIALIZATION VARCHAR(2000) COMMENT 'Materializetion type configured for dbt object.',
            DATABASE_NAME VARCHAR(2000) COMMENT 'Database name configured for dbt object.',
            SCHEMA VARCHAR(2000) COMMENT 'Schema name configured for dbt object.',
            ALIAS VARCHAR(2000) COMMENT 'Alias name configured for dbt object.',
            ERROR_MESSAGE VARCHAR(16777216) COMMENT 'Error message for dbt object.',
            ADAPTER_RESPONSE OBJECT COMMENT 'Response of the adapter.'
        )
        ;
    {% endcall %}
    {{ log("Audit Table '" ~ relation ~ "' Created Successfully", info=True) }}

    {# Building Insert Into Audit Table Query #}
    {%- set results_content_sql = get_audit_log_run_results_content_sql() -%}

    {{ log("Logging Completion Information from Results Context", info=True) }}
    {% call statement('invocation_result_insert_sql') %}
        INSERT INTO {{ relation }} (
            INVOCATION_ID,
            PROJECT_ID,
            PROJECT_NAME,
            ENVIRONMENT_ID,
            ENVIRONMENT_NAME,
            JOB_ID,
            JOB_NAME,
            OBJECT_UID,
            OBJECT_NAME,
            OBJECT_TYPE,
            {# OBJECT_STATUS, #}
            {# OBJECT_START_TIME, #}
            {# OBJECT_END_TIME, #}
            RUN_START_TIME,
            WAS_FULL_REFRESH,
            THREAD_ID,
            RUN_STATUS,
            COMPILE_START_TIME,
            RUN_END_TIME,
            DURATION,
            {# SOURCE_RECORD_COUNT, #}
            {# INSERT_RECORD_COUNT, #}
            {# UPDATE_RECORD_COUNT, #}
            {# ERROR_RECORD_COUNT, #}
            MATERIALIZATION,
            DATABASE_NAME,
            SCHEMA,
            ALIAS,
            ERROR_MESSAGE,
            ADAPTER_RESPONSE
        )
        VALUES
        {{ results_content_sql }}
        ;
    {% endcall %}

{% endmacro %}

{% macro get_audit_log_run_results_content_sql() %}
    {# By Using Context Variables, Environment Variables, and Snowflake Function #}
    {# Building Select Query for Audit Run End Macro #}
    {% set select_sql %}
    SELECT
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        PARSE_JSON($23)
    FROM VALUES

    {% for node_object in results | selectattr("node.resource_type", "in", supported_resource_types) | list %}
        (
            '{{ invocation_id }}', {# 1. command_invocation_id -- Context Variable #}
            '{{ env_var('DBT_CLOUD_PROJECT_ID', '') }}', {# 2. dbt_cloud_project_id #}
            '{{ project_name }}',
            '{{ env_var('DBT_CLOUD_ENVIRONMENT_ID', '') }}',
            '{{ target.name }}',
            '{{ env_var('DBT_CLOUD_JOB_ID', '') }}',
            '{{ env_var('DBT_CLOUD_JOB_NAME', '') }}',
            '{{ node_object.node.unique_id }}', {# 8. node_id #}
            '{{ node_object.node.name }}',
            '{{ node_object.node.resource_type }}',
            {# OBJECT_STATUS, #}
            {# OBJECT_START_TIME, #}
            {# OBJECT_END_TIME, #}
            '{{ run_started_at }}', {# 14. run_started_at -- Context Variable #}

            {% set config_full_refresh = node_object.node.config.full_refresh %}
            {% if config_full_refresh is none %}
                {% set config_full_refresh = flags.FULL_REFRESH %}
            {% endif %}
            '{{ config_full_refresh }}', {# 15. was_full_refresh #}

            '{{ node_object.thread_id }}', {# 16. thread_id #}
            '{{ node_object.status | upper }}', {# 17. status #}
            
            {% set compile_started_at = (node_object.timing | selectattr("name", "eq", "compile") | first | default({}))["started_at"] %}
            {% if compile_started_at %}'{{ compile_started_at }}'{% else %}null{% endif %}, {# 18. compile_started_at #}
            
            {% set query_completed_at = (node_object.timing | selectattr("name", "eq", "execute") | first | default({}))["completed_at"] %}
            {% if query_completed_at %}'{{ query_completed_at }}'{% else %}null{% endif %}, {# 19. query_completed_at #}

            {{ node_object.execution_time }}, {# 20. total_node_runtime #}
            {# SOURCE_RECORD_COUNT, #}
            {# INSERT_RECORD_COUNT, #}
            {# UPDATE_RECORD_COUNT, #}
            {# ERROR_RECORD_COUNT, #}
            '{{ node_object.node.config.materialized }}',
            '{{ node_object.node.config.database }}',
            '{{ node_object.node.config.schema }}',
            '{{ node_object.node.config.alias }}',
            '{{ node_object.message | replace("\\", "\\\\") | replace("'", "\\'") | replace('"', '\\"') }}', {# 29. message #}
            '{{ tojson(node_object.adapter_response) | replace("\\", "\\\\") | replace("'", "\\'") | replace('"', '\\"') }}' {# 30. adapter_response #}
        )
        {%- if not loop.last %},{%- endif %}

    {% endfor %}
    {% endset %}

    {{ select_sql }}

{% endmacro %}