
{{
    config(
        materialized='custom_merge_material',
        alias=var('DBT_ALIAS_NAME'),
        database='DBT_DB_DEV',
        schema='SILVER',
        unique_key=['PLATFORM_NAME','SCHEDULE_NAME','JOB_NAME'],
        exclude_update=['JOB_SCHEDULE_ID','INSERTED_BY','INSERT_DATE'],
        exclude_insert=['JOB_SCHEDULE_ID']
    )
}}

SELECT 
'DBT' AS PLATFORM_NAME,
NULL AS SCHEDULE_NAME,
DBTJOBS.NAME AS JOB_NAME,
DBTJOBS.JOB_TYPE AS JOB_TYPE,
NULL AS "ENVIRONMENTNAME",
NULL AS "VERSIONNAME",
DBTPRJ.PROJECT_NAME AS PROJECTNAME,
DBTJOBS.EXECUTE_STEPS AS COMMAND_DETAILS,
DBTJOBS.TRIGGERS_SCHEDULE AS ENABLED,
NULL AS "DAYSOFMONTH",
NULL AS "DAYOFWEEK", 
NULL AS "SUNDAY", 
NULL AS "MONDAY",
NULL AS "TUESDAY",
NULL AS "WEDNESDAY",
NULL AS "THURSDAY",
NULL AS "FRIDAY",
NULL AS "SATURDAY", 
NULL AS "HOUR", 
NULL AS "MINUTE",
DBTJOBS.CRON_HUMANIZED AS INTERVAL,
NULL AS FREQUENCY,
NULL AS TIMEZONE,
DBTJOBS.SCHEDULE_CRON AS CRON_SCHEDULE,
DBTJOBS.CREATED_AT AS CREATED,
DBTJOBS.UPDATED_AT AS LASTALTERED,
NULL AS DELETED, 
NULL AS IS_AUTOINGEST_ENABLED,
CURRENT_USER() AS INSERTED_BY,
CURRENT_USER() AS UPDATED_BY,
NULL AS COMMENTS,
CURRENT_TIMESTAMP() AS INSERT_DATE,
CURRENT_TIMESTAMP() AS UPDATE_DATE
FROM 
(SELECT * FROM {{ source('DBT_API_METADATA', 'DBT_JOBS') }}
WHERE UPPER(TRIGGERS_SCHEDULE)='TRUE' AND UPPER(JOB_TYPE)='SCHEDULED') DBTJOBS
LEFT JOIN
(SELECT ID AS PROJECT_ID,NAME AS PROJECT_NAME FROM
{{ source('DBT_API_METADATA', 'DBT_PROJECTS') }}) DBTPRJ
ON DBTJOBS.PROJECT_ID=DBTPRJ.PROJECT_ID