{{
    config(
        materialized='view',
        database='DBT_DB_DEV',
        schema='DBT_API_METADATA',
        alias='VW_DBT_API_METADATA'
    )
}}

SELECT 
DBTACT.ID AS ACCOUNT_ID,
DBTACT.NAME AS ACCOUNT_NAME,
DBTPRJ.ID AS PROJECT_ID,
DBTPRJ.NAME AS PROJECT_NAME,
DBTENV.ID AS ENVIRONMENT_ID,
DBTENV.NAME AS ENVIRONMENT_NAME,
DBTJOBS.ID AS JOB_ID,
DBTJOBS.NAME AS JOB_NAME
FROM
{{ source('DBT_API_METADATA', 'DBT_ACCOUNTS') }} AS DBTACT
JOIN
{{ source('DBT_API_METADATA', 'DBT_PROJECTS') }} AS DBTPRJ
ON DBTACT.ID=DBTPRJ.ACCOUNT_ID
JOIN
{{ source('DBT_API_METADATA', 'DBT_ENVIRONMENTS') }} AS DBTENV
ON DBTACT.ID=DBTENV.ACCOUNT_ID 
AND DBTPRJ.ID=DBTENV.PROJECT_ID
LEFT JOIN
{{ source('DBT_API_METADATA', 'DBT_JOBS') }} AS DBTJOBS
ON DBTACT.ID=DBTJOBS.ACCOUNT_ID 
AND DBTPRJ.ID=DBTJOBS.PROJECT_ID
AND DBTENV.ID=DBTJOBS.ENVIRONMENT_ID